# docker-compose.yml
# version: "3.9"

networks:
  hackzion_net:
    driver: bridge

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - hackzion_net
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    expose:
      - "8000"
    networks:
      - hackzion_net
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
      - honeypot
      - detection
      - response
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - hackzion_net
    restart: unless-stopped

  honeypot:
    build:
      context: .
      dockerfile: ./honeypot/Dockerfile
    expose:
      - "9001"
    networks:
      - hackzion_net
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  detection:
    build:
      context: .
      dockerfile: ./detection/Dockerfile
    expose:
      - "8001"
    networks:
      - hackzion_net
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    ports:
      - "8001:8001"

  response:
    build:
      context: .
      dockerfile: ./response/Dockerfile
    expose:
      - "8002"
    networks:
      - hackzion_net
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    ports:
      - "8002:8002"